dist: trusty

language: generic

sudo: required

before_install:
    - sudo pip install bashate
    
script:
 - sudo bash ./integration-tests/int-bashate.sh
 - sudo bash ./integration-tests/int-apps-install-uninstall.sh
 
matrix:
  fast_finish: true
